# Generated by Django 4.1.6 on 2023-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_jw_user_image_alter_jw_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jw_user",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="jw_user",
            name="status",
            field=models.CharField(
                choices=[("대기", "대기"), ("승인", "승인"), ("거절", "거절")],
                default="봉사의종",
                max_length=10,
            ),
        ),
    ]
