# Generated by Django 4.1.6 on 2023-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticeboard", "0002_rename_weekendmeeting_appointmentcongregation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CongregationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="congregation_group/")),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
